### ISSUE TITLE
Support EC keys in SSH.com and Putty format

### ISSUE THREAD

**Issue by adiroiban** [chevah/chevah-keycert#38]
and all the other format that we support... both reading but also writing

**Comment by adiroiban** [comment]
Putty support was added in #48 ... but I don't know what is the format for SSH.com for EDCSA and ED.

We might need to use Tectia.

We have a licence of Tectia ... but I am not sure where it is installed.

@dumol can you help with SSH.com format for ECDSA and ED ? Do you know where our Tectia SSH is installed . Maybe @lgheorghiu  knows :)

**Comment by dumol** [comment]
https://trac.chevah.com/wiki/Infrastructure/Services/FileTransferServers#tectia-ssh says it should be available at 172.20.1.100:1122, but it's not listening there.

Found it installed on the `winci` VM, and tried to start it from the desktop icon, but got _Your evaluation period has ended_.

Further digging shows the licence was not renewed on purpose. More at https://trac.chevah.com/ticket/4640#comment:5.

**Comment by dumol** [comment]
For the record, I've recovered access to the my.ssh.com account. Put licences for both server and client on the `winci` VM. Everything is functional again, as documented, but with a non-expiring licence.
