### ISSUE TITLE
Add support for EC keys

### ISSUE THREAD

**Issue by adiroiban** [chevah/chevah-keycert#39]
See code from here https://cryptography.io/en/latest/_modules/cryptography/hazmat/primitives/asymmetric/ec/?highlight=generate_private_key

I guess that we can have all curve types supported by Python cryptography.

@dumol do you have any suggestion for the default curve type?

Generate , read in OpenSSH format, sign / verify

**Comment by dumol** [comment]
Sorry, haven't seen this at the time! 

I use Curve25519 with my Ed25519 SSH key generated and managed with GnuPG. It's also the default in OpenSSH for ECDH keys. Don't recall how I chose it, but this seems relatable: https://stribika.github.io/2015/01/04/secure-secure-shell.html.

Might this be it? https://cryptography.io/en/latest/hazmat/primitives/asymmetric/ed25519/

**Comment by dumol** [comment]
An interesting matrix: https://ssh-comparison.quendi.de/comparison/kex.html

**Comment by adiroiban** [comment]
Thanks. I will go with Ed25519

**Comment by dumol** [comment]
_Recommended Curves_ from IETF's _Elliptic Curves for Security_ also goes for Curve25519. More at https://tools.ietf.org/html/rfc7748#section-4

**Comment by adiroiban** [comment]
This ticket is for adding 

```
   * ecdsa-sha2-nistp256
   * ecdsa-sha2-nistp384
   * ecdsa-sha2-nistp521
  ```

Ed25519 will be done in #42
